# Generated by Django 4.2.7 on 2023-11-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
